src/XHouse/Backup/XHouseWeb/Controllers/AmbientesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using Ninject;
using XHouse.Data.Interfaces;
using XHouse.Model;
using XHouseWeb.Helpers;

namespace XHouseWeb.Controllers
{
    public class AmbientesController : Controller
    {
        private readonly IRepository<Ambiente> _repositorio;
        private readonly ImageProvider _imageProvider;

        [Inject]
        public AmbientesController(IRepository<Ambiente> repository, ImageProvider imageProvider)
        {
            if (repository == null)
                throw new ArgumentNullException("repository");

            if (imageProvider == null)
                throw new ArgumentNullException("imageProvider");

            _imageProvider = imageProvider;
            _repositorio = repository;
        }

        //
        // GET: /Ambientes/
        public ActionResult Index()
        {
            // FIXME: Ese "x => true" es cualquiera. Es un workarround, habría que hacen un GetAll que devuelva un IQueryable
            return View(_repositorio.GetQueryable(x => true).Include(a => a.Aparatos));
        }

        //
        // GET: /Aparatos/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Aparatos/Create
        [HttpPost]
        public ActionResult Create(Ambiente ambiente)
        {
            // Chequeo si existe otro ambiente con el mismo nombre
            if (!string.IsNullOrEmpty(ambiente.Nombre) && _repositorio.Get(x => x.Nombre.Equals(ambiente.Nombre, StringComparison.OrdinalIgnoreCase)).Any())
                ModelState.AddModelError("AmbienteRepetido", string.Format("Ya existe un ambiente con el nombre <strong>{0}</strong>.", ambiente.Nombre));

            var guardarArchivo = false;
            HttpPostedFileBase file = null;

            // Si hay un archivo, chequeo que sea válido
            if (Request.Files != null && Request.Files.Count > 0)
            {
                file = Request.Files[0];
                if (file != null && file.ContentLength > 0)
                {
                    string[] errorMsg;

                    if (!_imageProvider.ValidateFile(file, out errorMsg))
                    {
                        for (var i = 0; i < errorMsg.Length; i++)
                            ModelState.AddModelError(string.Format("ErrorArchivo-{0}", i), errorMsg[i]);
                    }
                    else
                        guardarArchivo = true;
                }
            }

            // Chequeo si hay errores de validación
            if (!ModelState.IsValid)
                return View(ambiente);

            // Guardo el ambiente
            _repositorio.Add(ambiente);
            _repositorio.Save();

            // Guardo la imagen
            if (guardarArchivo)
                _imageProvider.Save(file, ambiente.Id, ImagenTipoObjeto.Ambiente);

            return RedirectToAction("Index");
        }

        //
        // GET: /Ambientes/Edit/5
        public ActionResult Edit(int id = 0)
        {
            var ambiente = _repositorio.GetQueryable(x => x.Id == id).Include(a => a.Aparatos).First();
            if (ambiente == null)
                return HttpNotFound();

            if (_imageProvider.HaveImage(ImagenTipoObjeto.Ambiente, id))
                ViewBag.SrcImagen = _imageProvider.GetImagePath(ImagenTipoObjeto.Ambiente, id);
            
            return View(ambiente);
        }

        //
        // POST: /Ambientes/Edit/5
        [HttpPost]
        public ActionResult Edit(Ambiente ambiente)
        {
            // Chequeo si existe otro ambiente con el mismo nombre
            if (!string.IsNullOrEmpty(ambiente.Nombre) && _repositorio.Get(x => x.Nombre.Equals(ambiente.Nombre, StringComparison.OrdinalIgnoreCase) && x.Id != ambiente.Id).Any())
                ModelState.AddModelError("AmbienteRepetido", string.Format("Ya existe un ambiente con el nombre <strong>{0}</strong>.", ambiente.Nombre));

            bool borrarImagenAnterior;
            if (!bool.TryParse(Request.Form["hidBorrarImagen"], out borrarImagenAnterior))
                borrarImagenAnterior = false;

            var guardarArchivo = false;
            HttpPostedFileBase file = null;

            if (!_imageProvider.HaveImage(ImagenTipoObjeto.Ambiente, ambiente.Id) || borrarImagenAnterior)
            {
                // Si hay un archivo, chequeo que sea válido
                if (Request.Files != null && Request.Files.Count > 0)
                {
                    file = Request.Files[0];
                    if (file != null && file.ContentLength > 0)
                    {
                        string[] errorMsg;

                        if (!_imageProvider.ValidateFile(file, out errorMsg))
                        {
                            for (var i = 0; i < errorMsg.Length; i++)
                                ModelState.AddModelError(string.Format("ErrorArchivo-{0}", i), errorMsg[i]);
                        }
                        else
                            guardarArchivo = true;
                    }
                }
            }

            // Chequeo si hay errores de validación
            if (!ModelState.IsValid)
                return View(ambiente);

            // Guardo el ambiente
            _repositorio.Update(ambiente);
            _repositorio.Save();

            // Eliminar imagen anterior
            if (borrarImagenAnterior)
                _imageProvider.Remove(ambiente.Id, ImagenTipoObjeto.Ambiente);

            // Guardo la imagen
            if (guardarArchivo)
                _imageProvider.Save(file, ambiente.Id, ImagenTipoObjeto.Ambiente);

            return RedirectToAction("Index");
        }

        //
        // GET: /Ambientes/Delete/5
        public ActionResult Delete(int id)
        {
            Ambiente ambiente = _repositorio.Get(id);
            if (ambiente == null)
                return HttpNotFound();

            using (var tran = new TransactionScope())
            {
                _repositorio.Remove(id);
                _repositorio.Save();

                _imageProvider.Remove(ambiente.Id, ImagenTipoObjeto.Ambiente);

                tran.Complete();
            }
            
            return RedirectToAction("Index");
        }

        //
        // GET: /Escenas/Configure
        public ActionResult Configure(int id)
        {
            var ambiente = _repositorio.Get(id);

            // Imagen de la Ambiente
            ViewBag.PathImagen = Url.Content(_imageProvider.GetImagePath(ImagenTipoObjeto.Ambiente, ambiente.Id));

            // Imagenes de los tipos de aparatos involucrados en la Ambiente
            var pathImgTipoAparatos = new Dictionary<int, string>();

            foreach (var a in ambiente.Aparatos)
            {
                if (pathImgTipoAparatos.ContainsKey(a.TipoAparatoId))
                    continue;

                pathImgTipoAparatos.Add(a.TipoAparatoId,
                                        Url.Content(_imageProvider.GetImagePath(ImagenTipoObjeto.TipoAparato,
                                                                                a.TipoAparatoId)));
            }

            ViewBag.PathImgTipoAparatos = pathImgTipoAparatos;

            return View(ambiente);
        }

        protected override void Dispose(bool disposing)
        {
            _repositorio.Dispose();
            base.Dispose(disposing);
        }
    }
    
}

src/XHouse/Backup/XHouseWeb/Controllers/AparatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Ninject;
using XHouse.Data.Interfaces;
using XHouse.Model;
using XHouse.Model.Aparatos;

namespace XHouseWeb.Controllers
{
    public class AparatosController : Controller
    {
        private readonly IRepository<Aparato> _repositorioAparatos;
        private readonly IRepository<Zona> _repositorioZonas;
        private readonly IRepository<TipoAparato> _repositorioTipoAparatos;
        private readonly IRepository<Modulo> _repositorioModulos;
        private readonly IRepository<Ambiente> _repositorioAmbientes;
        private readonly IRepository<TipoAparato> _tipoAparato;

        [Inject]
        public AparatosController(IRepository<Aparato> repAparatos, IRepository<Zona> repZonas, IRepository<TipoAparato> repTipoAparatos, IRepository<Modulo> repModulos, IRepository<Ambiente> repAmbientes)
        {
            if (repAparatos == null)
                throw new ArgumentNullException("repAparatos");

            if (repZonas == null)
                throw new ArgumentNullException("repZonas");

            if (repTipoAparatos == null)
                throw new ArgumentNullException("repTipoAparatos");

            if (repTipoAparatos == null)
                throw new ArgumentNullException("repModulos");

            if (repTipoAparatos == null)
                throw new ArgumentNullException("repAmbientes");
            
            _repositorioAparatos = repAparatos;
            _repositorioZonas = repZonas;
            _repositorioTipoAparatos = repTipoAparatos;
            _repositorioModulos = repModulos;
            _repositorioAmbientes = repAmbientes;
        }


        //
        // GET: /Aparatos/
        public ActionResult Index()
        {
            var apar = _repositorioAparatos.GetAll();
            // TODO: Ver si es necesario levantar la zona asociada
            //aparatos.AsQueryable<Aparato>().Include(a => a.Zona);
            return View(apar.ToList());
        }

        //
        // GET: /Aparatos/Details/5

        public ActionResult Details(int id = 0)
        {
            Aparato aparato = _repositorioAparatos.Get(id);
            if (aparato == null)
            {
                return HttpNotFound();
            }
            return View(aparato);
        }

        //
        // GET: /Aparatos/Create
        public ActionResult Create()
        {
            ViewBag.Zonas = _repositorioZonas.GetAll();
            ViewBag.TiposAparatos = _repositorioTipoAparatos.GetAll();
            ViewBag.Modulos = _repositorioModulos.GetAll();
            ViewBag.Ambientes = _repositorioAmbientes.GetAll();
            return View();
        }

        //
        // POST: /Aparatos/Create

        [HttpPost]
        public ActionResult Create(Aparato aparato)
        {
            if (ModelState.IsValid)
            {
                _repositorioAparatos.Add(aparato);
                _repositorioAparatos.Save();

                return RedirectToAction("Index");
            }

            ViewBag.ZonaId = new SelectList(_repositorioZonas.GetAll(), "Id", "Nombre", aparato.ZonaId);
            return View(aparato);
        }

        //
        // GET: /Aparatos/Edit/5
        public ActionResult Edit(int id = 0)
        {
            Aparato aparato = _repositorioAparatos.Get(id);
            if (aparato == null)
            {
                return HttpNotFound();
            }

            ViewBag.Zonas = _repositorioZonas.GetAll();
            ViewBag.TiposAparatos = _repositorioTipoAparatos.GetAll();
            ViewBag.Modulos = _repositorioModulos.GetAll();
            ViewBag.Ambientes = _repositorioAmbientes.GetAll();
            return View(aparato);
        }

        //
        // POST: /Aparatos/Edit/5

        [HttpPost]
        public ActionResult Edit(Aparato aparato)
        {
            if (ModelState.IsValid)
            {
                aparato.TipoAparato = _repositorioTipoAparatos.Get(aparato.TipoAparatoId);

                _repositorioAparatos.Update(aparato);
                _repositorioAparatos.Save();;
                return RedirectToAction("Index");
            }

            return View(aparato);
        }

        //
        // GET: /Aparatos/Delete/5
        public ActionResult Delete(int id)
        {
            _repositorioAparatos.Remove(id);
            _repositorioAparatos.Save();

            return RedirectToAction("Index");
        }

        // GET: /Aparatos/Get/1
        public JsonResult Get(int id)
        {
            var a = _repositorioAparatos.Get(id);
            dynamic result = new
                {
                    id = a.Id,
                    tipoId = a.TipoAparatoId,
                    nombre = a.Nombre,
                    numero = a.Numero,
                    habilitado = a.Habilitado,
                    estado = a.EstadoActual
                };

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        // POST: /Aparatos/Save
        [HttpPost]
        public JsonResult Save(Aparato a)
        {
            return null;
        }

        [HttpPost]
        public void Posicionar(Aparato posApar)
        {
            if (posApar.Id <= 0)
                return;

            var a = _repositorioAparatos.Get(posApar.Id);
            a.PosicionX = posApar.PosicionX;
            a.PosicionY = posApar.PosicionY;

            _repositorioAparatos.Update(a);
            _repositorioAparatos.Save();
        }

        protected override void Dispose(bool disposing)
        {
            _repositorioAparatos.Dispose();
            _repositorioZonas.Dispose();
            base.Dispose(disposing);
        }
    }
}

src/XHouse/Backup/XHouseWeb/Views/Ambientes/Configure.cshtml
@model XHouse.Model.Ambiente

@{
    ViewBag.Title = "Configurar Ambiente";
}

<style>
    .draggable { width: 30px; z-index: 1}

    #droppable { padding: 0.5em; }

    .seleccionado {
        border: solid 2px red;
    }
    
    .posicionado {
    }
</style>

<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">
    <div class="page-header">
      <h3>Configurar Ambiente</h3>
    </div>
    
    <!-- Columna izquierda -->
    <div class="col-lg-2">
      <h4 class="mb20">Aparatos</h4>
      
      <div id="lista-aparatos">
      @* Agrego a la lista de aparatos los aparatos no posicionados. *@
      @foreach (var a in Model.Aparatos.Where(a => !a.Posicionado))
      {
        <div style="margin-bottom: 5px;" class="ui-widget-content">
          <img id="aparato-@a.Id" src="@ViewBag.PathImgTipoAparatos[a.TipoAparatoId]" alt="A" class="draggable"/>
          <span>@a.Nombre</span>
        </div>
      }
            
      @* Agrego a la lista de aparatos los aparatos posicionados dentro de la imagen de la zona. *@
      @foreach (var a in Model.Aparatos.Where(a => a.Posicionado))
      {
        <div style="margin-bottom: 5px;" class="ui-widget-content">
          <img id="aparato-@a.Id" src="@ViewBag.PathImgTipoAparatos[a.TipoAparatoId]" alt="A" class="draggable posicionado" style="position: relative; left: @(a.PosicionX)px; top: @(a.PosicionY)px;"/>
          <span>@a.Nombre</span>
        </div>
      }
    </div>

    </div>
    
    <!-- Columna central (imagen) -->
    <div class="col-lg-8">
      <h4 class="mb10">Ambiente</h4>
      <div id="droppable">
        <img src="@ViewBag.PathImagen" alt="Ambiente" style="width: 100%;"/>
      </div>
    </div>
    
    <!-- Columna derecha (configuración) -->
    <div class="col-lg-2">
      <h4 class="mb20">Información</h4>

      <label id="aparato-nombre" style="font-weight: bold">Nombre del aparatos (1234)</label>
      <span id="aparato-tipo" class="help-block">(Tipo de Aparato)</span>
    </div>
    
  </div>
</div>

@section Scripts
{
  <script src="~/Scripts/jquery-ui-1.10.3.min.js"></script>
  <script type="text/javascript">
    $(function() {

      $('.draggable').click(function() {
        actualizarSeleccion(this);

        var idAparato = $(this)[0].id.replace('aparato-', '');
        mostrarConfigAparato(idAparato);
      });

      // Hago que las imágenes de los artefactos sean draggables
      $(".draggable").draggable({
        revert: "invalid",
        stop: function() {
          // Evento que surge cuando se para de arrastrar, siempre
        }
      });

      // Inicialización del objecto droppable (la imagen de la zona)
      $("#droppable").droppable({
        drop: function(event, ui) {
          $(this).addClass("posicionado");

          var apar = { "Id": getAparatoId(ui.draggable[0].id), "PosicionX": ui.position.left, "PosicionY": ui.position.top };
          
          $.ajax({
            type: "POST",
            url: "@Url.Action("Posicionar", "Aparatos")",
            data: apar,
            accept: 'application/json'
          });
        }
      });
    });

    function actualizarSeleccion(apar) {
      $('.posicionado').removeClass("seleccionado");
      $(apar).addClass('seleccionado');
    }

    function mostrarConfigAparato(id) {
      // Obtengo la lista de Tipos de Aparatos disponibles
      $.getJSON('/Aparatos/Get/' + id, function(a) {

        $.getJSON('/TipoAparatos/Get/' + a.tipoId, function(ta) {
          $('#aparato-nombre').html(a.nombre + ' (' + a.numero + ')');
          $('#aparato-tipo').html(ta.nombre);
        });
      });
    }
    
    function getAparatoId(idElemento) {
      return parseInt(idElemento.split('-')[1]);
    }
  </script>
}

src/XHouse/Backup/XHouseWeb/Views/Ambientes/Create.cshtml
@model XHouse.Model.Ambiente

@{
    ViewBag.Title = "Nuevo Ambiente";
}

<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">
    
    <div class="page-header">
      <h3>Nuevo Ambiente</h3>
    </div>

    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", @role = "form", enctype = "multipart/form-data" }))
    {
      if (ViewData.ModelState != null && !ViewData.ModelState.IsValid)
      { 
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @Html.ValidationSummary(false, "Errores:")
        </div>
      }
      
      <div class="form-group">
        <label class="col-lg-2 control-label" for="Nombre">@Html.DisplayNameFor(model => model.Nombre)</label>
        <div class="col-lg-4">
          @Html.TextBoxFor(model => model.Nombre, new {@class = "form-control"})
        </div>
      </div>
      
      <div class="form-group">
        <label class="col-lg-2 control-label" for="Descripcion">@Html.DisplayNameFor(model => model.Descripcion)</label>
        <div class="col-lg-4">
          @Html.TextAreaFor(model => model.Descripcion, new {@class = "form-control"})
        </div>
      </div>
      
      <div class="form-group">
        <label class="col-lg-2 control-label" for="imagen">Imagen del ambiente</label>
        <div class="col-lg-6">
          <input type="file" name="imagen">
          <p class="help-block">Solo se permiten archivos de imagen. La imagen será redimensionada.</p>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-3">
          <button class="btn btn-primary" type="submit">Guardar</button>
          <a class="btn btn-danger" href="@Url.Action("Index")">Cancelar</a>
        </div>
      </div>
    }

  </div>
</div>

src/XHouse/Backup/XHouseWeb/Views/Ambientes/Edit.cshtml
@model XHouse.Model.Ambiente

@{
    ViewBag.Title = "Editar Ambiente";
}

<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">
    
    <div class="page-header">
      <h3>Editar Ambiente</h3>
    </div>
    
    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", @role = "form", enctype = "multipart/form-data" }))
    {
      if (ViewData.ModelState != null && !ViewData.ModelState.IsValid)
      { 
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          @Html.ValidationSummary(false, "Errores:")
        </div>
      }

      <div class="form-group">
        <label class="col-lg-2 control-label">Ambiente #</label>
        <div class="col-lg-4">
          <p class="form-control-static">
            @Html.DisplayTextFor(model => model.Id)
          </p>
        </div>
      </div>
      
      <div class="form-group">
        <label class="col-lg-2 control-label" for="Nombre">@Html.DisplayNameFor(model => model.Nombre)</label>
        <div class="col-lg-4">
          @Html.TextBoxFor(model => model.Nombre, new {@class = "form-control"})
        </div>
      </div>
      
      <div class="form-group">
        <label class="col-lg-2 control-label" for="Descripcion">@Html.DisplayNameFor(model => model.Descripcion)</label>
        <div class="col-lg-4">
          @Html.TextAreaFor(model => model.Descripcion, new {@class = "form-control"})
        </div>
      </div>
      
      <div class="form-group">
        <label class="col-lg-2 control-label">Cantidad de Aparatos: </label>
        <div class="col-lg-1">
          <p class="form-control-static">@(Model.Aparatos != null ? Model.Aparatos.Count.ToString() : "0")</p>
        </div>
      </div>

      @Html.Hidden("hidBorrarImagen")

      <div class="form-group">
        <label class="col-lg-2 control-label" for="imagen">Imagen del ambiente</label>
          
        @* Div que se muestra cuando hay una imagen *@
        <div id="divImagenActual" class="col-lg-4" style="display: @(ViewBag.SrcImagen == null || string.IsNullOrEmpty(ViewBag.SrcImagen) ? "none;" : "block;") ">
          <button type="button" class="close" id="btnQuitarImagen" aria-hidden="true"
                  style="margin-right:5px; margin-top:2px;" onclick="quitarImagen();">&times;</button>
          <a href="#" class="thumbnail">
            <img data-src="holder.js/100%x180" alt="Imagen del ambiente" 
              src="@(ViewBag.SrcImagen == null || string.IsNullOrEmpty(ViewBag.SrcImagen) ? "#" : Url.Content(ViewBag.SrcImagen))">
          </a>
        </div>
          
        @* Div que se muestra cuando no hay una imagen *@
        <div id="divIngresarImagen" class="col-lg-6" style="display: @(ViewBag.SrcImagen == null || string.IsNullOrEmpty(ViewBag.SrcImagen) ? "block;" : "none;") ">
          
          @if (ViewBag.SrcImagen != null || !string.IsNullOrEmpty(ViewBag.SrcImagen))
          {
            <div class="col-lg-8 alert alert-warning">Se ha quitado la imagen anterior (<a class="alert-link" href="javascript:deshacerQuitarImagen();">deshacer</a>).</div>
          }
          
          <input type="file" name="imagen">
          <p class="help-block">Solo se permiten archivos de imagen. La imagen será redimensionada.</p>
        </div>

      </div>
      
      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-3">
          <button class="btn btn-primary" type="submit">Guardar</button>
          <a class="btn btn-danger" href="@Url.Action("Index")">Cancelar</a>
        </div>
      </div>
    }

  </div>
</div>

@section Scripts
{
  <script type="text/javascript">
    function quitarImagen() {
      $('#hidBorrarImagen').val('true');
      $('#divImagenActual').hide();
      $('#divIngresarImagen').show();
    }

    function deshacerQuitarImagen() {
      $('#hidBorrarImagen').val('false');
      $('#divIngresarImagen').hide();
      $('#divImagenActual').show();
    }
  </script>
}

src/XHouse/Backup/XHouseWeb/Views/Ambientes/Index.cshtml
@model IEnumerable<XHouse.Model.Ambiente>

@{
    ViewBag.Title = "Ambientes";
}

<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">

    <h2>Ambientes</h2>

    <a class="btn btn-success white mt20 mb20" href="@Url.Action("Create", "Ambientes")" >
      <span class="glyphicon glyphicon-plus"></span> Nuevo Ambiente
    </a>

    <table class="table">
      <thead>
        <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>Descripción</th>
          <th>Cantidad de Aparatos</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
       @foreach (var i in Model)
       {
         <tr>
           <td>@i.Id</td>
           <td>@i.Nombre</td>
           <td>@i.Descripcion</td>
           <td>@i.Aparatos.Count</td>
           <td>
            <a class="btn btn-info btn-xs white" href="@Url.Action("Edit", "Ambientes", new { id = i.Id})">
              <span class="glyphicon glyphicon-pencil"></span> Editar
            </a>
            <a class="btn btn-warning btn-xs white" href="@Url.Action("Configure", "Ambientes", new { id = i.Id})">
              <span class="glyphicon glyphicon-cog"></span> Configurar
            </a>

              <!--Modifique la parte  de eliminar como esta por ejemplo en tipo aparato con eso es necesario-->
                          <a class="btn btn-danger btn-xs white" onclick="return confirm('¿Esta seguro que desea eliminar este Ambiente?');" href="@Url.Action("Delete", "Ambientes", new { id = i.Id })">
               <span class="glyphicon glyphicon-remove"></span> Eliminar
</a>
               <!-- Esto no va ademas no tiene para relanzar al stio que lo mandaba 
                    <a class="btn btn-danger btn-xs white" href="@Url.Action("Delete", "Ambientes", new { id = i.Id})">
                   <span class="glyphicon glyphicon-remove"></span> Eliminar
                                                                      </a>
    HASTA ACA no va este codigo lo dejo para ver los cambios-->
          </td>
         </tr>
       }
      </tbody>
    </table>

  </div>
</div>