src/XHouse/XHouseWeb/Controllers/EscenasController.cs
using System;
using System.Web.Mvc;
using Ninject;
using XHouse.Data.Interfaces;
using XHouse.Model;
using XHouse.Model.Escenas;
using XHouseWeb.Helpers;

namespace XHouseWeb.Controllers
{
    public class EscenasController : Controller
    {
        private readonly IRepository<Escena> _repositorio;
        

        [Inject]
        public EscenasController(IRepository<Escena> repository, ImageProvider imageProvider)
        {
            if (repository == null)
                throw new ArgumentNullException("repository");

            if (imageProvider == null)
                throw new ArgumentNullException("imageProvider");

            _repositorio = repository;
        }


        //
        // GET: /Escenas/

        public ActionResult Index()
        {
            return View(_repositorio.GetAll());
        }

        //
        // GET: /Escenas/Details/5

        public ActionResult Details(int id = 0)
        {
            Escena escena = _repositorio.Get(id);
            if (escena == null)
            {
                return HttpNotFound();
            }
            return View(escena);
        }

        //
        // GET: /Escenas/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Escenas/Create

        [HttpPost]
        public ActionResult Create(Escena escena)
        {
            if (ModelState.IsValid)
            {
                _repositorio.Add(escena);
                _repositorio.Save();
                return RedirectToAction("Index");
            }

            return View(escena);
        }

        //
        // GET: /Escenas/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Escena escena = _repositorio.Get(id);
            if (escena == null)
            {
                return HttpNotFound();
            }
            return View(escena);
        }

        //
        // POST: /Escenas/Edit/5

        [HttpPost]
        public ActionResult Edit(Escena escena)
        {
            if (ModelState.IsValid)
            {
                _repositorio.Update(escena);
                _repositorio.Save();

                return RedirectToAction("Index");
            }
            return View(escena);
        }

        //
        // GET: /Escenas/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Escena escena = _repositorio.Get(id);
            if (escena == null)
            {
                return HttpNotFound();
            }
            return View(escena);
        }

        //
        // POST: /Escenas/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _repositorio.Remove(id);
            _repositorio.Save();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _repositorio.Dispose();
            base.Dispose(disposing);
        }
    }
}

src/XHouse/XHouseWeb/Controllers/HistorialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ninject;
using XHouse.Data.Interfaces;
using XHouse.Model;

namespace XHouseWeb.Controllers
{
    public class HistorialController : Controller
    {
        protected IRepository<Historial> _repositorioHistorial; 

        public HistorialController(IRepository<Historial> repHistorial)
        {
            if (repHistorial == null)
                throw new ArgumentNullException("repHistorial");

            _repositorioHistorial = repHistorial;
        }
    

        //
        // GET: /Historial/
        public ActionResult Index()
        {
            var historialOrdenado = _repositorioHistorial.GetAll().OrderByDescending(h => h.Fecha);
            return View(historialOrdenado.ToList());
        }

        //
        // GET: /Historial/Details/5
        public ActionResult Details(int id)
        {
            var hist = _repositorioHistorial.Get(id);
            
            if (hist == null)
            {
                return HttpNotFound();
            }

            return View(hist);
        }
    }
}

src/XHouse/XHouseWeb/Controllers/ModulosController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Ninject;
using XHouse.Data.Interfaces;
using XHouse.Model;
using XHouse.Model.Aparatos;

namespace XHouseWeb.Controllers
{
    public class ModulosController : Controller
    {
        private readonly IRepository<Modulo> _repositorioModulos;
        private readonly IRepository<Aparato> _repositorioAparatos;

        [Inject]
        public ModulosController(IRepository<Modulo> repModulos, IRepository<Aparato> repAparatos)
        {
            if (repModulos == null)
                throw new ArgumentNullException("repModulos");

            if (repModulos == null)
                throw new ArgumentNullException("repModulos");

            _repositorioModulos = repModulos;
            _repositorioAparatos = repAparatos;
        }


        //
        // GET: /Modulos/
        public ActionResult Index()
        {
            var modulos = _repositorioModulos.GetAll();
            return View(modulos.ToList());
        }

        //
        // GET: /Modulos/Details/5

        public ActionResult Details(int id = 0)
        {
            Modulo modulo = _repositorioModulos.Get(id);
            if (modulo == null)
            {
                return HttpNotFound();
            }

            // Incluyo los aparatos asociados al modulo, ya que voy a mostrar el detalle
            modulo.Aparatos = _repositorioAparatos.GetQueryable(a => a.ModuloId == id).Include(a => a.TipoAparato);
            
            return View(modulo);
        }

        //
        // GET: /Modulos/Create
        public ActionResult Create()
        {
            // Setear lo comboboxes
            return View();
        }

        //
        // POST: /Modulos/Create

        [HttpPost]
        public ActionResult Create(Modulo modulo)
        {
            if (!ModelState.IsValid)
                return View(modulo);

            // Chequeo que no haya otro modulo con el mismo nombre ya ingresado
            if (_repositorioModulos.Get(m => m.Nombre == modulo.Nombre).Any())
            {
                ModelState.AddModelError(string.Empty, string.Format("Ya existe un Módulo con el nombre <b>{0}</b>.", modulo.Nombre));
                return View(modulo);
            }

            // Chequeo que no haya otro módulo con la misma dirección
            if (_repositorioModulos.Get(m => m.Direccion == modulo.Direccion).Any())
            {
                ModelState.AddModelError(string.Empty, string.Format("Ya existe un Módulo la dirección <b>{0}</b>.", modulo.Direccion));
                return View(modulo);
            }

            // No hay errores en el modelo
            _repositorioModulos.Add(modulo);
            _repositorioModulos.Save();

            return RedirectToAction("Index");
        }

        //
        // GET: /Modulos/Edit/5
        public ActionResult Edit(int id = 0)
        {
            Modulo modulo = _repositorioModulos.Get(id);

            if (modulo == null)
            {
                return HttpNotFound();
            }

            return View(modulo);
        }

        //
        // POST: /Modulos/Edit/5

        [HttpPost]
        public ActionResult Edit(Modulo modulo)
        {
            if (!ModelState.IsValid)
                return View(modulo);

            // Chequeo que no haya otro modulo con el mismo nombre ya ingresado
            if (_repositorioModulos.Get(m => m.Nombre == modulo.Nombre && m.Id != modulo.Id).Any())
            {
                ModelState.AddModelError(string.Empty, string.Format("Ya existe un Módulo con el nombre <b>{0}</b>.", modulo.Nombre));
                return View(modulo);
            }

            // Chequeo que no haya otro módulo con la misma dirección
            if (_repositorioModulos.Get(m => m.Direccion == modulo.Direccion && m.Id != modulo.Id).Any())
            {
                ModelState.AddModelError(string.Empty, string.Format("Ya existe un Módulo la dirección <b>{0}</b>.", modulo.Direccion));
                return View(modulo);
            }

            _repositorioModulos.Update(modulo);
            _repositorioModulos.Save();;
            return RedirectToAction("Index");
        }

        //
        // GET: /Modulos/Delete/5
        public ActionResult Delete(int id)
        {
            _repositorioModulos.Remove(id);
            _repositorioModulos.Save();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _repositorioModulos.Dispose();
            base.Dispose(disposing);
        }

    }
}

src/XHouse/XHouseWeb/Controllers/ZonasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Ninject;
using XHouse.Data.Interfaces;
using XHouse.Model;
using XHouseWeb.Helpers;

namespace XHouseWeb.Controllers
{
    public class ZonasController : Controller
    {
        private readonly IRepository<Zona> _repositorio;
        private readonly ImageProvider _imageProvider;
        
        [Inject]
        public ZonasController(IRepository<Zona> repository, ImageProvider imageProvider)
        {
            if (repository == null)
                throw new ArgumentNullException("repository");

            if (imageProvider == null)
                throw new ArgumentNullException("imageProvider");

            _imageProvider = imageProvider;
            _repositorio = repository;
        }

        //
        // GET: /Zonas/

        public ActionResult Index()
        {
            return View(_repositorio.GetAll());
        }

        //
        // GET: /Zonas/Details/5

        public ActionResult Details(int id = 0)
        {
            Zona zona = _repositorio.Get(id);
            if (zona == null)
            {
                return HttpNotFound();
            }
            return View(zona);
        }

        //
        // GET: /Zonas/Create
        public ActionResult Create()
        {
            return View();
        }

        
        //
        // POST: /Zonas/Create
        [HttpPost]
        public ActionResult Create(Zona zona)
        {
            //if (ModelState.IsValid)
            //{
            //    _repositorio.Add(zona);
            //    _repositorio.Save();

            //    return RedirectToAction("Index");
            //}

            //return View(zona);
            if (!ModelState.IsValid)
                return View(zona);

            if (_repositorio.Get(m => m.Nombre == zona.Nombre).Any())
            {
                ModelState.AddModelError(string.Empty, string.Format("Ya existe una Zona con el nombre <b>{0}</b>.", zona.Nombre));
                return View(zona);
            }

            // No hay errores en el modelo
            _repositorio.Add(zona);
            _repositorio.Save();

            return RedirectToAction("Index");
        }

        //
        // GET: /Zonas/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Zona zona = _repositorio.Get(id);
            if (zona == null)
            {
                return HttpNotFound();
            }
            return View(zona);
        }

        //
        // POST: /Zonas/Edit/5

        [HttpPost]
        public ActionResult Edit(Zona zona)
        {
            if (!ModelState.IsValid)
                return View(zona);

            // Chequeo que no haya otro zona con el mismo nombre ya ingresado
            if (_repositorio.Get(m => m.Nombre == zona.Nombre && m.Id != zona.Id).Any())
            {
                ModelState.AddModelError(string.Empty, string.Format("Ya existe una Zona con el nombre <b>{0}</b>.", zona.Nombre));
                return View(zona);
            }

            _repositorio.Update(zona);
            _repositorio.Save();
            return RedirectToAction("Index");
        }

        //
        // GET: /Zonas/Delete/5

        public ActionResult Delete(int id)
        {
            Zona zona = _repositorio.Get(id);
            if (zona == null)
            {
                return HttpNotFound();
            }
            else
            {
                _repositorio.Remove(id);
                _repositorio.Save();
                return RedirectToAction("Index");
            }
        }

        //
        // GET: /Escenas/Configure
        public ActionResult Configure(int id)
        {
            Zona zona = _repositorio.Get(id);

            // Imagen de la zona
            ViewBag.PathImagen = Url.Content(_imageProvider.GetImagePath(ImagenTipoObjeto.Ambiente, zona.Id));

            // Imagenes de los tipos de aparatos involucrados en la zona
            var pathImgTipoAparatos = new Dictionary<int, string>();

            foreach (var a in zona.Aparatos)
            {
                if (pathImgTipoAparatos.ContainsKey(a.TipoAparatoId))
                    continue;

                pathImgTipoAparatos.Add(a.TipoAparatoId,
                                        Url.Content(_imageProvider.GetImagePath(ImagenTipoObjeto.TipoAparato,
                                                                                a.TipoAparatoId)));
            }

            ViewBag.PathImgTipoAparatos = pathImgTipoAparatos;

            return View(zona);
        }

        protected override void Dispose(bool disposing)
        {
            _repositorio.Dispose();
            base.Dispose(disposing);
        }
    }
}

src/XHouse/XHouseWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - SIIA</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap -->
    <link href="~/Content/bootstrap/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/bootstrap/bootstrap-theme.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/base.css" rel="stylesheet"/>

    <!-- Para que la barra del tope no tape el contenido -->
    <style type="text/css">
      body { padding-top: 70px; }
    </style>
  </head>
  <body>
    <script type="text/javascript" src="~/Scripts/jquery-2.0.3.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>

    @Html.Partial("_NavBar")
    @RenderBody()
    @RenderSection("Scripts", false)
  </body>
</html> 

src/XHouse/XHouseWeb/Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="@Url.Action("Index", "Home")">SIIA</a>
    </div>

    @if (Request.IsAuthenticated)
    {
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                @{ var currentController = ViewContext.RouteData.Values["controller"].ToString().ToLower(); }

                <li class="@(currentController.Equals("escenas") ? "active" : "")"><a href="@Url.Action("Index", "Escenas")"><span class="glyphicon glyphicon-eye-open"></span>Escenas</a></li>
                <li class="@(currentController.Equals("ambientes") ? "active" : "")"><a href="@Url.Action("Index", "Ambientes")"><span class="glyphicon glyphicon-picture"></span>Ambientes</a></li>
                <li class="@(currentController.Equals("historial") ? "active" : "")"><a href="@Url.Action("Index", "Historial")"><span class="glyphicon glyphicon-floppy-disk"></span>Historial</a></li>

                <li class="dropdown @(currentController.Equals("aparatos") ||
                                      currentController.Equals("modulos") ||
                                      currentController.Equals("zonas") ||
                                      currentController.Equals("tipoaparatos") ? "active" : "")">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span>Administración <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("Index", "Aparatos")">Aparatos</a></li>
                        <li><a href="@Url.Action("Index", "Modulos")">Modulos</a></li>
                        <li><a href="@Url.Action("Index", "Zonas")">Zonas</a></li>
                        <li><a href="@Url.Action("Index", "TipoAparatos")">Tipos de Aparatos</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav pull-right">
                <!-- Login -->
                <li class="dropdown">
                    @Html.Partial("_LoginPartial")
                </li>
                <li>
                    <span style="font-size: 32px">|</span>
                </li>
                <!-- Hora -->
                <li>
                    <p class="navbar-text" id="clock"></p>
                </li>
            </ul>
        </div>
    
        
    }
    else
    {
        <div>
        <ul class="nav navbar-nav pull-right">
                <!-- Login -->
                <li class="dropdown">
                    @Html.Partial("_LoginPartial")
                </li>
                <li>
                    <span style="font-size: 32px">|</span>
                </li>
                <!-- Hora -->
                <li>
                    <p class="navbar-text" id="clock"></p>
                </li>
            </ul>
        </div>
    }

</nav>

<script>
    $(document).ready(function () {
        $('#dropdown-login').find('form').click(function (e) {
            e.stopPropagation();
        });

        actualizarFechaYHora();
        setInterval('actualizarFechaYHora()', 1000);
    });

    function actualizarFechaYHora() {
        var currentTime = new Date();
        var currentHours = currentTime.getHours();
        var currentMinutes = currentTime.getMinutes();
        var currentSeconds = currentTime.getSeconds();

        currentMinutes = (currentMinutes < 10 ? "0" : "") + currentMinutes;
        currentSeconds = (currentSeconds < 10 ? "0" : "") + currentSeconds;
        currentHours = (currentHours < 10 ? "0" : "") + currentHours;
        var currentTimeString = currentHours + ":" + currentMinutes + ":" + currentSeconds;

        var monthNames = ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"];
        var dayNames = ["Dom", "Lun", "Mar", "Mie", "Jue", "Vie", "Sab"];
        var currentDateString = dayNames[currentTime.getDay()] + " " + currentTime.getDate() + ' ' + monthNames[currentTime.getMonth()];

        $("#clock").html('<span class="glyphicon glyphicon-time"></span> ' + currentTimeString);
        //$("#date").html(currentDateString);
    }
</script>

src/XHouse/XHouseWeb/Views/Shared/_StartMenuPartial.cshtml
@{
 string controlador = ViewContext.Controller.ValueProvider.GetValue("controller").RawValue.ToString();
 string accion = ViewContext.Controller.ValueProvider.GetValue("action").RawValue.ToString();
}

@* Si estoy en la Home, oculto el menú que permite ir hacia atras *@
@if (controlador.Equals("Home", StringComparison.OrdinalIgnoreCase) && accion.Equals("Index", StringComparison.OrdinalIgnoreCase))
{
    <h1>¡Bienvenido a SIIA!</h1>
}
else
{
    <a id="backbutton" class="win-backbutton" href="@Url.Action("Index","Home")"></a>
    <h5>SIIA</h5>
    <div class="dropdown">
        <a class="header-dropdown dropdown-toggle accent-color" data-toggle="dropdown" href="#">
            Inicio
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li>@Html.ActionLink("Escenas", "Index", "Escenas")</li>
            <li>@Html.ActionLink("Historial", "Index", "Historial")</li>
            <li>@Html.ActionLink("Zonas", "Index", "Zonas")</li>
            <li>@Html.ActionLink("Aparatos", "Index", "Aparatos")</li>
            <li>@Html.ActionLink("Módulos", "Index", "Modulos")</li>
            <li>@Html.ActionLink("Tipo Aparatos", "Index", "TipoAparatos")</li>
        </ul>
    </div>
}