src/XHouse/Backup/XHouseWeb/Controllers/TipoAparatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Ninject;
using XHouse.Data.Interfaces;
using XHouse.Model;
using XHouse.Model.Aparatos;
using XHouseWeb.Helpers;


namespace XHouseWeb.Controllers
{
    public class TipoAparatosController : Controller
    {
        private readonly IRepository<TipoAparato> _repositorioTipoAparato;
        private readonly ImageProvider _imageProvider;

        [Inject]
        public TipoAparatosController(IRepository<TipoAparato> repTipoAparato, ImageProvider imageProvider)
        {
            if (repTipoAparato == null)
                throw new ArgumentNullException("repTipoAparato");

            if (imageProvider == null)
                throw new ArgumentNullException("imageProvider");

            _imageProvider = imageProvider;
            _repositorioTipoAparato = repTipoAparato;
        }


        //
        // GET: /TipoAparatos/
        public ActionResult Index()
        {
            var tipoAparatos = _repositorioTipoAparato.GetAll();
            return View(tipoAparatos.ToList());
        }

        //
        // GET: /TipoAparatos/Details/5

        public ActionResult Details(int id = 0)
        {
            TipoAparato tipoAparato = _repositorioTipoAparato.Get(id);
            if (tipoAparato == null)
            {
                return HttpNotFound();
            }
            return View(tipoAparato);
        }

        //
        // GET: /TipoAparatos/Create
        public ActionResult Create()
        {
            // Setear lo comboboxes
            return View();
        }

        //
        // POST: /TipoAparatos/Create

        [HttpPost]
        public ActionResult Create(TipoAparato tipoAparato)
        {
            if (!ModelState.IsValid)
                return View(tipoAparato);

            // Chequeo que no haya otro aparato con el mismo nombre ya ingresado
            if (_repositorioTipoAparato.Get(ta => ta.Nombre == tipoAparato.Nombre).Any())
            {
                ModelState.AddModelError(string.Empty, string.Format("Ya existe un Tipo de Aparato con el nombre {0}.", tipoAparato.Nombre));
                return View(tipoAparato);
            }

            // No hay errores en el modelo
            _repositorioTipoAparato.Add(tipoAparato);
            _repositorioTipoAparato.Save();

            return RedirectToAction("Index");
        }

        //
        // GET: /TipoAparatos/Edit/5
        public ActionResult Edit(int id = 0)
        {
            TipoAparato tipoAparato = _repositorioTipoAparato.Get(id);
            if (tipoAparato == null)
            {
                return HttpNotFound();
            }
           
            return View(tipoAparato);
        }

        //
        // POST: /TipoAparatos/Edit/5

        [HttpPost]
        public ActionResult Edit(TipoAparato tipoAparato)
        {
            if (!ModelState.IsValid)
                return View(tipoAparato);

            // Chequeo que no haya otro aparato con el mismo nombre ya ingresado
            if (_repositorioTipoAparato.Get(ta => ta.Nombre == tipoAparato.Nombre).Any())
            {
                ModelState.AddModelError(string.Empty, string.Format("Ya existe un Tipo de Aparato con el nombre {0}.", tipoAparato.Nombre));
                return View(tipoAparato);
            }

            _repositorioTipoAparato.Update(tipoAparato);
            _repositorioTipoAparato.Save();;
            return RedirectToAction("Index");
        }

        //
        // GET: /TipoAparatos/Delete/5
        public ActionResult Delete(int id)
        {
            _repositorioTipoAparato.Remove(id);
            _repositorioTipoAparato.Save();

            return RedirectToAction("Index");
        }

        // GET: /TipoAparatos/Get
        public JsonResult Get(int id)
        {
            var ta = _repositorioTipoAparato.Get(id);
            dynamic result = new
                {
                    id = ta.Id,
                    nombre = ta.Nombre,
                    operacion = ta.Operacion.ToString(),
                    puedeApagarse = ta.PuedeApagarse,
                    estadoApagado = ta.EstadoApagado,
                    topeInferior = ta.RangoTopeInferior,
                    topeSuperior = ta.RangoTopeSuperior
                };
            
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            _repositorioTipoAparato.Dispose();
            base.Dispose(disposing);
        }

    }

}

src/XHouse/Backup/XHouseWeb/Views/TipoAparatos/Create.cshtml
@using XHouse.Model.Aparatos
@using XHouseWeb.App_Code
@model TipoAparato

@{
    ViewBag.Title = "Nuevo Tipo de Aparato";
}



<div class="row">
<div class="col-xs-12 col-md-10 col-md-offset-1">
    <div class="page-header">
        <h3>Nuevo Tipo de Aparato</h3>
    </div>
    @using (Html.BeginForm(null, null, FormMethod.Post, new {@class = "form-horizontal", @role = "form"}))
    {
        if (ViewData.ModelState != null && !ViewData.ModelState.IsValid)
        {

            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                @Html.Raw(HttpUtility.HtmlDecode((Html.ValidationSummary(false, "Errores:") ?? (object) "").ToString()))
            </div>
        }

        //@Html.HiddenFor(model => model.Id)


        <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.Nombre).ToString()) ? null : "has-error")">
            <label for="Nombre" class="col-lg-2 control-label">Nombre</label>
            <div class="col-lg-3">
                @Html.TextBoxFor(model => model.Nombre, new {@class = "form-control"})
            </div>

        </div>
        <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.Descripcion).ToString()) ? null : "has-error")">
            <label for="Descripcion" class="col-lg-2 control-label">Descripción</label>
            <div class="col-lg-3">
                @Html.TextBoxFor(model => model.Descripcion, new {@class = "form-control"})
            </div>

        </div>
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-3">
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(model => model.Habilitado) Habilitado
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.Operacion).ToString()) ? null : "has-error")">
            <label for="Tipo" class="col-lg-2 control-label">Operación</label>
            <div class="col-lg-3">
                @Html.DropDownListFor(model => model.Operacion, TipoOperacion.Binario.ToSelectList(), new {@class = "form-control"})
            </div>
        </div>

        <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.RangoTopeInferior).ToString()) ? null : "has-error")">
            <label for="RangoTopeInferior" class="col-lg-2 control-label">Rango Tope Inferior</label>
            <div class="col-lg-3">
                @Html.TextBoxFor(model => model.RangoTopeInferior, new {@class = "form-control"})
            </div>

        </div>

        <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.RangoTopeSuperior).ToString()) ? null : "has-error")">
            <label for="RangoTopeSuperior" class="col-lg-2 control-label">Rango Tope Superior</label>
            <div class="col-lg-3">
                @Html.TextBoxFor(model => model.RangoTopeSuperior, new {@class = "form-control"})
            </div>

        </div>

        <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.Conexion).ToString()) ? null : "has-error")">
            <label for="Tipo" class="col-lg-2 control-label">Conexión</label>
            <div class="col-lg-3">
                @Html.DropDownListFor(model => model.Conexion, TipoConexion.Entrada.ToSelectList(), new {@class = "form-control"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-3">
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(model => model.PuedeApagarse) Puede Apagarse
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.EstadoApagado).ToString()) ? null : "has-error")">
            <label for="EstadoApagado" class="col-lg-2 control-label">Estado Apagado</label>
            <div class="col-lg-3">
                @Html.TextBoxFor(model => model.EstadoApagado, new {@class = "form-control"})
            </div>

        </div>

        
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-3">
                <button class="btn btn-primary">Guardar</button>
                <!--ACA AGREGUE ADEMAS DE ACTION ANTES QUE AGRREGUE EL ID EN VEZ ANTES DE LA DEFINICION DE LAS CAJAS
                    PARAR CARGAR LOS OTROS DATOS POR TECLADO-->
                <a class="btn btn-danger" href="@Html.HiddenFor(model => model.Id), @Url.Action("Index") ">Cancelar</a>
            </div>
        </div>

    }        

</div>
</div>

src/XHouse/Backup/XHouseWeb/Views/TipoAparatos/Delete.cshtml
@model XHouse.Model.Aparatos.TipoAparato

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>TipoAparato</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Descripcion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Descripcion)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Habilitado)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Habilitado)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RangoTopeInferior)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RangoTopeInferior)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RangoTopeSuperior)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RangoTopeSuperior)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PuedeApagarse)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PuedeApagarse)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EstadoApagado)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EstadoApagado)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

src/XHouse/Backup/XHouseWeb/Views/TipoAparatos/Details.cshtml
@model XHouse.Model.Aparatos.TipoAparato

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>TipoAparato</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Descripcion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Descripcion)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Habilitado)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Habilitado)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RangoTopeInferior)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RangoTopeInferior)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RangoTopeSuperior)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RangoTopeSuperior)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PuedeApagarse)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PuedeApagarse)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EstadoApagado)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EstadoApagado)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/XHouse/Backup/XHouseWeb/Views/TipoAparatos/Edit.cshtml
@using XHouseWeb.App_Code
@model XHouse.Model.Aparatos.TipoAparato

@{
    ViewBag.Title = "Editar Tipo de Aparato";
}

<div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
        <div class="page-header">
            <h3>Editar Tipo de Aparato</h3>
        </div>
        @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
        {
            if (ViewData.ModelState != null && !ViewData.ModelState.IsValid)
            { 
               
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                @Html.Raw(HttpUtility.HtmlDecode((Html.ValidationSummary(false, "Errores:") ?? (object)"").ToString()))
            </div>
            }
            
            @Html.HiddenFor(model => model.Id)
    
                        
            <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.Nombre).ToString()) ? null : "has-error")">
                <label for="Nombre" class="col-lg-2 control-label">Nombre</label>
                <div class="col-lg-3">
                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
                </div>

            </div>
            <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.Descripcion).ToString()) ? null : "has-error")">
                <label for="Descripcion" class="col-lg-2 control-label">Descripción</label>
                <div class="col-lg-3">
                    @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control" })
                </div>

            </div>
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-3">
                    <div class="checkbox">
                        <label> 
                            @Html.CheckBoxFor(model => model.Habilitado) Habilitado
                        </label>
                    </div>
                </div>
            </div>
            
            <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.Operacion).ToString()) ? null : "has-error")">
                <label for="Tipo" class="col-lg-2 control-label">Operación</label>
                <div class="col-lg-3">
                    @Html.DropDownListFor(model => model.Operacion, Model.Operacion.ToSelectList(), new { @class = "form-control" })
                </div>
            </div>
            
            <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.RangoTopeInferior).ToString()) ? null : "has-error")">
                <label for="RangoTopeInferior" class="col-lg-2 control-label">Rango Tope Inferior</label>
                <div class="col-lg-3">
                    @Html.TextBoxFor(model => model.RangoTopeInferior, new { @class = "form-control" })
                </div>

            </div>
            
            <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.RangoTopeSuperior).ToString()) ? null : "has-error")">
                <label for="RangoTopeSuperior" class="col-lg-2 control-label">Rango Tope Superior</label>
                <div class="col-lg-3">
                    @Html.TextBoxFor(model => model.RangoTopeSuperior, new { @class = "form-control" })
                </div>

            </div>
            
            <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.Conexion).ToString()) ? null : "has-error")">
                <label for="Tipo" class="col-lg-2 control-label">Conexión</label>
                <div class="col-lg-3">
                    @Html.DropDownListFor(model => model.Conexion, Model.Conexion.ToSelectList(), new { @class = "form-control" })
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-3">
                    <div class="checkbox">
                        <label> 
                            @Html.CheckBoxFor(model => model.PuedeApagarse) Puede Apagarse
                        </label>
                    </div>
                </div>
            </div>
            
            <div class="form-group @(Html.ViewData.ModelState.IsValidField(Html.IdFor(model => model.EstadoApagado).ToString()) ? null : "has-error")">
                <label for="EstadoApagado" class="col-lg-2 control-label">Estado Apagado</label>
                <div class="col-lg-3">
                    @Html.TextBoxFor(model => model.EstadoApagado, new { @class = "form-control" })
                </div>

            </div>
            
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-3">
                    <button class="btn btn-primary">Guardar</button>
                    <a class="btn btn-danger" href="@Url.Action("Index")">Cancelar</a>
                </div>
            </div>
                   
        }

    </div>
</div>

src/XHouse/Backup/XHouseWeb/Views/TipoAparatos/Index.cshtml
@model IEnumerable<XHouse.Model.Aparatos.TipoAparato>

@{
    ViewBag.Title = "Tipo de Aparatos";
}


<div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">

        <h3>Tipo de Aparatos</h3>

        <a class="btn btn-success white mt20 mb20" href="@Url.Action("Create", "TipoAparatos")">
            <span class="glyphicon glyphicon-plus"></span> Nuevo Tipo de Aparato
        </a>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Tipo Aparato</th>
                        <th>Habilitado</th>
                        <th>Rango Tope Inferior</th>
                        <th>Rango Tope Superior</th>
                        <th>Puede Apagarse</th>
                        <th>Estado Apagado</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                            <td>@Html.DisplayFor(modelItem => item.Habilitado)</td>
                            <td>@Html.DisplayFor(modelItem => item.RangoTopeInferior)</td>
                            <td>@Html.DisplayFor(modelItem => item.RangoTopeSuperior)</td>
                            <td>@Html.DisplayFor(modelItem => item.PuedeApagarse)</td>
                            <td>@Html.DisplayFor(modelItem => item.EstadoApagado)</td>
                            <td>
                                <a class="btn btn-info btn-xs white" href="@Url.Action("Edit", "TipoAparatos", new { id = item.Id })">
                                    <span class="glyphicon glyphicon-pencil"></span> Editar
                                </a>
                    
                                <a class="btn btn-danger btn-xs white" onclick="return confirm('¿Esta seguro que desea eliminar el tipo de aparato?');" href="@Url.Action("Delete", "TipoAparatos", new { id = item.Id })">
                                    <span class="glyphicon glyphicon-remove"></span> Eliminar
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>